[WFCORE-2517] Coverity, Dereference after null check (Elytron subsystem)
wildfly-security-incubator/wildfly-core pull request #110
Opened 2017-03-30 12:22 UTC by ivassile

wildfly-core: https://issues.jboss.org/browse/WFCORE-2517
JBEAP: https://issues.jboss.org/browse/JBEAP-9475

2017-03-30 17:14 UTC, darranl requested changes
Are we sure the XML parsing should be skipped?

2017-03-30 17:14 UTC, darranl commented on elytron/src/main/java/org/wildfly/extension/elytron/PolicyParser.java
> +        {
Minor issue with the formatting.

2017-03-30 17:14 UTC, darranl commented on elytron/src/main/java/org/wildfly/extension/elytron/PolicyParser.java
> +        } else {
This change doesn't feel quite correct - it skips the rest of the XML parsing are we sure that it should be skipped?

2017-03-30 21:40 UTC, ivassile commented
Submitted the requested changes.

2017-04-03 16:31 UTC, kabir approved these changes

2017-04-04 11:07 UTC, merged