[WFCORE-2427] remove URI attribute from credential store resource
wildfly-security-incubator/wildfly-core pull request #139
Opened 2017-04-19 20:10 UTC by pskopek

https://issues.jboss.org/browse/JBEAP-6907
https://issues.jboss.org/browse/WFCORE-2427

2017-04-19 20:32 UTC, kabir requested changes

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            boolean modifiable = asBooleanIfDefined(context, MODIFIABLE, model);
If not defined, this method seems to return `false` while the default value for the attribute  is `true`. `true` should be used if not defined.

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
> +        credentialStoreAttributes.put(ElytronDescriptionConstants.MODIFIABLE, Boolean.toString(modifiable));
Does it matter that this could overwrite entries from implementationAttributes?

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
> +        credentialStoreAttributes.put(ElytronDescriptionConstants.CREATE, Boolean.toString(create));
As above

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.modifiable=Specifies whether credential store is modifiable (true | false).
true/false not really needed - it is covered by the type=boolean in :read-resource-description

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.create=Specifies whether credential store should create storage when it doesn't exist (true | false).
true/false not needed

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            boolean create = asBooleanIfDefined(context, CREATE, model);
Here `false` is correctly used.
I think I would just do here and above 
MODIFIABLE.resolveModelAttribute(context, model).asBoolean(MODIFIABLE.getDefaultValue().asBoolean());
CREATE.resolveModelAttribute(context, model).asBoolean(CREATE.getDefaultValue().asBoolean());

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
> +    static boolean asBooleanIfDefined(OperationContext context, SimpleAttributeDefinition attributeDefinition, ModelNode model) throws OperationFailedException {
If you follow my other suggestions this method is not needed any more

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
> +        <xs:attribute name="modifiable" type="xs:boolean" use="optional">
Needs default=true

2017-04-19 20:32 UTC, kabir commented on elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
> +        <xs:attribute name="create" type="xs:boolean" use="optional">
Needs default=false

2017-04-19 20:32 UTC, kabir commented on elytron/src/test/resources/org/wildfly/extension/elytron/tls-test.xml
> +        <credential-store name="test" case-sensitive="false" location="target/tlstest.keystore">
Just to be sure the parsing and marshalling works properly, I'd like to see the `create` and `modifiable` attributes used in the test xml as well.

2017-04-19 20:43 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            boolean modifiable = asBooleanIfDefined(context, MODIFIABLE, model);
asBooleanIfDefined calls attributeDefinition.resolveModelAttribute, which means if there is a default value it won't return undefined.

2017-04-19 20:44 UTC, kabir commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            boolean modifiable = asBooleanIfDefined(context, MODIFIABLE, model);
ah!

2017-04-19 20:46 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            boolean modifiable = asBooleanIfDefined(context, MODIFIABLE, model);
But, given that this could just be:

boolean modifiable = MODIFIABLE.resolveModelAttribute(context, model).asBoolean();

2017-04-19 20:47 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            boolean create = asBooleanIfDefined(context, CREATE, model);
If you know MODIFIABLE has a default value there is no reason to do anything other than

boolean modifiable = MODIFIABLE.resolveModelAttribute(context, model).asBoolean();

Same for CREATE.

The contract of resolveModeAttribute is to return any default if the value in the model is undefined.

2017-04-19 20:50 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            String location = asStringIfDefined(context, LOCATION, model);
Just an FYI, with DMR 1.4.0 the whole asStringIfDefined could go away and you can just use

String location = LOCATION.resolveModelAttribute(context, model).asStringOrNull();

The various ModelNode asXXXOrNull() return null if the node is undefined.

No need to change this; it's just an FYI.

2017-04-20 05:57 UTC, pskopek commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
> +        credentialStoreAttributes.put(ElytronDescriptionConstants.MODIFIABLE, Boolean.toString(modifiable));
Yes, it was meant to override both "create" and "modifiable".

2017-04-20 05:57 UTC, pskopek commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
> +        credentialStoreAttributes.put(ElytronDescriptionConstants.CREATE, Boolean.toString(create));
Yes, it was meant to override both "create" and "modifiable".

2017-04-20 05:57 UTC, pskopek commented on elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
> +    static boolean asBooleanIfDefined(OperationContext context, SimpleAttributeDefinition attributeDefinition, ModelNode model) throws OperationFailedException {
removed

2017-04-20 05:58 UTC, pskopek commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.modifiable=Specifies whether credential store is modifiable (true | false).
removed

2017-04-20 05:58 UTC, pskopek commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.create=Specifies whether credential store should create storage when it doesn't exist (true | false).
removed

2017-04-20 05:59 UTC, pskopek commented on elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
> +        <xs:attribute name="modifiable" type="xs:boolean" use="optional">
added

2017-04-20 06:00 UTC, pskopek commented on elytron/src/main/resources/schema/wildfly-elytron_1_0.xsd
> +        <xs:attribute name="create" type="xs:boolean" use="optional">
added

2017-04-20 06:34 UTC, pskopek commented on elytron/src/test/resources/org/wildfly/extension/elytron/tls-test.xml
> +        <credential-store name="test" case-sensitive="false" location="target/tlstest.keystore">
added

2017-04-20 06:47 UTC, pskopek commented
@kabir @bstansberry I have updated the PR with all suggestions.

2017-04-20 08:15 UTC, kabir approved these changes

2017-04-20 08:15 UTC, merged