[WFCORE-2671] key-managers:init, ssl-context:key-refresh
wildfly-security-incubator/wildfly-core pull request #146
Opened 2017-04-25 13:25 UTC by honza889

Added management operations allowing to change SSL key on runtime:
* key-managers:init
* ssl-context:key-refresh

2017-04-27 14:27 UTC, kabir approved these changes
Approving paperwork

2017-04-28 12:13 UTC, darranl commented on elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
> +            .Builder.of(KEY_MANAGERS_CAPABILITY, true, InjectedValue.class) // InjectedValue<KeyManager[]>
TBH I am not completely sure about this one - by switching to InjectedValue we are loosing the capability typing.  I think we may need to see if we have alternatives that can avoid loosing the type information.

2017-05-03 11:16 UTC, darranl requested changes
Still thinking about this one, I don't think we should loose the type information from the capability - I think we need to find an alternative to handle this.

2017-05-03 12:56 UTC, honza889 commented on elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
> +            .Builder.of(KEY_MANAGERS_CAPABILITY, true, InjectedValue.class) // InjectedValue<KeyManager[]>
What if I add special injector type, like `KeyManagersInjector` ? Will it be sufficient solution?

2017-05-09 09:56 UTC, honza889 commented on elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
> +            .Builder.of(KEY_MANAGERS_CAPABILITY, true, InjectedValue.class) // InjectedValue<KeyManager[]>
@darranl Will be suggested solution sufficient?

2017-05-16 08:57 UTC, kabir commented
@darranl @honza889 it is marked for the beta, so please give some consideration again

2017-05-16 17:30 UTC, darranl commented
I think I will mention in chat - rather than relying on a different type being injected I think we should look at a custom KeyStore implementation so we can still inject a KeyStore but then add a type check and cast.  We already have atomic keystores, maybe we can add something that also supports notifications?

2017-05-17 09:23 UTC, honza889 commented
[HALT] rework in progress

2017-05-17 20:12 UTC, honza889 commented
Reworked as requested, tests green, so prepared for merge now.

2017-05-18 13:58 UTC, merged