[WFCORE-2777] credential-store operations instead of alias resources
wildfly-security-incubator/wildfly-core pull request #158
Opened 2017-05-12 10:45 UTC by honza889

https://issues.jboss.org/browse/WFCORE-2777

need coordiantion with ?

2017-05-16 08:55 UTC, kabir approved these changes
Approving paperwork

2017-05-16 15:05 UTC, bstansberry requested changes
I made a ton of comments here but mostly they are the same minor things repeated.

The "throw RuntimeException not OFE" thing is a problem in the subsystem prior to this patch, but this seems like a good time to at least partially correct it.

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +    static final SimpleOperationDefinition READ_ALIASES = new SimpleOperationDefinitionBuilder(ElytronDescriptionConstants.READ_ALIASES, RESOURCE_RESOLVER)
.setRuntimeOnly()

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            .setParameters(ALIAS, ENTRY_TYPE, SECRET_VALUE)
.setRuntimeOnly()

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            .setParameters(ALIAS)
.setRuntimeOnly()

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +            .setParameters(ALIAS, ENTRY_TYPE, SECRET_VALUE)
.setRuntimeOnly()

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
>                          throw new OperationFailedException(e);
This should throw a RuntimeException, not OFE. OFE should only be used for user errors, not server faults.

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +                        throw new OperationFailedException(e);
This should throw a RuntimeException, not OFE. OFE should only be used for user errors, not server faults.

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +                        throw ROOT_LOGGER.unableToCompleteOperation(e, e.getLocalizedMessage());
This should throw a RuntimeException, not OFE. OFE should only be used for user errors, not server faults.

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +                        throw ROOT_LOGGER.unableToCompleteOperation(e, e.getLocalizedMessage());
This should throw a RuntimeException, not OFE. OFE should only be used for user errors, not server faults.

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
> +                        throw ROOT_LOGGER.unableToCompleteOperation(e, e.getLocalizedMessage());
This should throw a RuntimeException, not OFE. OFE should only be used for user errors, not server faults.

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
> +    @Message(id = 920, value = "Credential alias \"%s\" of credential type \"%s\" does not exists in the store")
s/exists/exist

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
> +    OperationFailedException credentialDoesNotExists(String alias, String credentialType);
s/Exists/Exist

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.read-aliases=Read an aliases (entries) from a credential store.
s/an aliases/aliases/g

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.add-alias=Add alias to the credential store.
s/alias/an alias/g

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.add-alias.entry-type=Type of an credential (entry) stored in the credential store.
s/an/a

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.add-alias.secret-value=Secret value such as password.
s/password/a password/g

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.remove-alias=Remove an credential (entry) stored in the credential store.
s/an/a

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.set-secret=Set secret value of an credential (entry) stored in the credential store.
s/secret/the secret/g
s/an/a

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.set-secret.entry-type=Type of an credential (entry) stored in the credential store.
s/an/a

2017-05-16 15:05 UTC, bstansberry commented on elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
> +elytron.credential-store.set-secret.secret-value=Secret value such as password.
s/password/a password/g

2017-05-16 15:06 UTC, bstansberry commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
>      static final SimpleOperationDefinition RELOAD = new SimpleOperationDefinitionBuilder(ElytronDescriptionConstants.RELOAD, RESOURCE_RESOLVER)
This one is setRuntimeOnly() as well.

2017-05-16 16:59 UTC, honza889 commented
@bstansberry updated by comments

2017-05-16 17:37 UTC, honza889 commented
ehm... wrong rebase, sorry, will fix soon..

2017-05-17 19:06 UTC, bstansberry commented
@honza889 this branch is messed up now. 25 commits.

2017-05-17 19:11 UTC, bstansberry commented
@honza889 @darranl the last commit on this branch addresses all my previous comments, so please regard this as having my +1 once the branch is rebased and the other commits removed.

2017-05-17 19:12 UTC, darranl commented
Thanks @bstansberry, I am Ok without the rebase, I will be bringing ladybird up to date with master before I merge so git will handle the rest.

2017-05-18 13:58 UTC, merged