[WFCORE-2553] - There isnt possibility set entry-type for new entry i…
wildfly-security-incubator/wildfly-core pull request #83
Opened 2017-03-17 08:25 UTC by baranowb

…n Credential Store.

https://issues.jboss.org/browse/WFCORE-2553
https://issues.jboss.org/browse/JBEAP-6611

2017-03-23 10:21 UTC, pskopek requested changes

2017-03-23 10:21 UTC, pskopek commented on elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreAliasDefinition.java
> +                if (entryType == null || SUPPORTED_CREDENTIAL_TYPES[0].getCanonicalName().equals(entryType)) {
I would properly fill "allowedValues" for ENTRY_TYPE attribute (also discard "Other"). 
At line 77 change getName to getCanonicalName.

 Then check:
if (entryType == null || entryType.equals(PasswordCredential.class.getCanonicalName())

2017-03-28 12:16 UTC, baranowb commented
@pskopek  done.

2017-04-03 16:46 UTC, kabir commented
This has all the acks

2017-04-05 05:45 UTC, pskopek approved these changes

2017-04-05 17:57 UTC, merged